### ISSUE TITLE
Nutrition (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#372]
### General
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/8
- [ ] [Detection of nutritional table image](https://docs.google.com/document/d/1WgIxe5e9_p02bTLzQYI3SVWGRkarTH4_w8Tyx9RQU88/edit#heading=h.7qg7yia69ttv)
- [ ] [Extraction of nutritional information from nutritional tables](https://docs.google.com/document/d/1ElWLLvHlWFbuTK1Frk-ejo6yeAWJy5KfPRTCXrc0WwI/edit)
- [ ] [Extraction of nutritional information from “text” nutritional tables](https://docs.google.com/document/d/125jaIQWGpc6LmdUo8N0TfaFReJc_q6mp71eC74qPr2s/edit#heading=h.v1gnxd5wv5v7)
### Integration of existing models
- [ ] https://github.com/openfoodfacts/robotoff/issues/300
- [ ] https://github.com/openfoodfacts/robotoff/issues/299

### Supporting detections (Regex based)
- [ ] Create a data model to store all the nutrition predictions
- [ ] [Detect portion size](https://docs.google.com/document/d/14QvARHkVfVt0xlsME6k3COA-Oh9ZZnFDBCyfVE0kPtM/edit#heading=h.lny9b6pqbwcy)
- [ ] Attempt to detect alcohol volume
- [ ] Detect products to be diluted
- [ ] Extract nutrients with units or clear patterns (kcal, kJ, % of various things, Proteins:12g if category avg is 12g)
- [ ] Extract presence of nutrient
- [ ] https://github.com/openfoodfacts/robotoff/issues/164
- [ ] https://github.com/openfoodfacts/robotoff/issues/93
- [ ] https://github.com/openfoodfacts/robotoff/issues/152
- [ ] https://github.com/openfoodfacts/robotoff/issues/83
- [ ] https://github.com/openfoodfacts/robotoff/issues/151
- [ ] https://github.com/openfoodfacts/robotoff/issues/11
- [ ] Unselect an image if no nutritional clue is found

### Datasets
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/issues/17

### Nutri-Score
- [ ] https://github.com/openfoodfacts/robotoff/issues/115
- [ ] https://github.com/openfoodfacts/robotoff/issues/317
- [ ] Psychic Nutri-Score (try guessing the category to compute immediately the Nutri-Score)
