### ISSUE TITLE
Tests (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#830]
### What

```[tasklist]
### Testing tasks
- [x] https://github.com/openfoodfacts/robotoff/issues/804
- [x] https://github.com/openfoodfacts/robotoff/issues/789
- [x] https://github.com/openfoodfacts/robotoff/issues/649
   -  [x] #833 
- [x] https://github.com/openfoodfacts/robotoff/issues/490
- [x] https://github.com/openfoodfacts/robotoff/issues/336
- [ ] https://github.com/openfoodfacts/robotoff/issues/214
```

#### Test the framework

```[tasklist]
### Test the framework
```

#### Test the individual ML models

```[tasklist]
### Test the individual ML models
```

### Why 
- Release with high confidence, ideally every week or two weeks

### Part of
- #374
